apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # service available only inside of a cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
