apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: ddemiurge/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.99.104.252" - using hardcoded IP that was defined by a service
              value: "auth-service.default" # using built-int DNS name of a service
            - name: TASKS_FOLDER
              value: tasks
